### ISSUE TITLE
看穿式采集的库应该放在哪里？

### ISSUE THREAD

**Issue by ChetWang** [ktrader-tech/jctp#4]
看穿式采集需要用到专用的库，如linux下是LinuxDataCollect.so，ctp直连期货公司柜台，不需要额外的调用，在登录的时候自动会采集信息。但是这个库要存在，请问这个库应该放在哪里？

**Comment by RationalityFrontline** [comment]
![image](https://user-images.githubusercontent.com/69410606/175487940-91e7f9c8-f7d3-4819-9ccc-7f13df9906be.png)
你是在开发中继类型终端？只有这个类型需要加载采集链接库，其它的都不用加载的
