### ISSUE TITLE
关于库的版本问题

### ISSUE THREAD

**Issue by K68** [ktrader-tech/jctp#7]
感谢作者制作的库，对Java开发友好，文档也清晰

我刚接触期货开发，对各种库的版本区别有点模糊

比如下面两个相同版本号，但是多了一个_CP 的后缀，请问这两个库有什么区别吗？分别用在什么对接场景呢

6.6.9-1.0.5
6.6.9_CP-1.0.5

**Comment by RationalityFrontline** [comment]
前者用在实盘生产环境，后者用在穿透式仿真测评环境。在实盘账户开通 CTP 程序化交易时，需要先在仿真测评环境里测试并填表发给期货公司才行。
